GET http://localhost:3000/comments HTTP/1.1

###
GET http://localhost:3000/comments?parentId=x67fa42c2677586bc69ff4800 HTTP/1.1


###
POST http://localhost:3000/comments HTTP/1.1
content-type: application/json

{
  "text": "new comment inside the second comment ",
  "userId":"67fa12168f52250dada8e9db",
  "parentId":"67fa42c2677586bc69ff4800"
}
